#ifndef FILTER_BUILDER_DURATION_SCALE_H
#define FILTER_BUILDER_DURATION_SCALE_H

#include <ctype.h>
#include <errno.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>

/* Recognize only the timestamp forms generated by the app and their simple
 * constant-speed equivalents. Never guess that an arbitrary expression is
 * affine by evaluating it at a few sample points. */
static int filter_builder_positive_number(const char *text, const char **end, double *value)
{
    char *tail;
    int parenthesized = *text == '(';
    if (parenthesized) text++;
    errno = 0;
    *value = strtod(text, &tail);
    if (tail == text || errno || !isfinite(*value) || *value <= 0)
        return -1;
    if (parenthesized && *tail++ != ')')
        return -1;
    *end = tail;
    return 0;
}

static int filter_builder_duration_scale(const char *expression, double *scale)
{
    char text[256];
    const char *bases[] = {"(PTS-STARTPTS)", "PTS-STARTPTS", "PTS"};
    const char *tail;
    double number;
    size_t length = 0;
    if (!expression || !scale) return -1;
    for (; *expression; expression++) {
        if (isspace((unsigned char)*expression)) continue;
        if (length + 1 >= sizeof(text)) return -1;
        text[length++] = *expression;
    }
    text[length] = '\0';
    for (unsigned i = 0; i < sizeof(bases) / sizeof(*bases); i++) {
        size_t n = strlen(bases[i]);
        if (strcmp(text, bases[i]) == 0) { *scale = 1; return 0; }
        /* An unparenthesized PTS-STARTPTS/2 divides only STARTPTS. */
        if (i == 1) continue;
        if (strncmp(text, bases[i], n) == 0 && (text[n] == '/' || text[n] == '*') &&
            filter_builder_positive_number(text + n + 1, &tail, &number) == 0 && !*tail) {
            *scale = text[n] == '/' ? 1 / number : number;
            return isfinite(*scale) && *scale > 0 ? 0 : -1;
        }
        if (filter_builder_positive_number(text, &tail, &number) == 0 &&
            *tail == '*' && strcmp(tail + 1, bases[i]) == 0) {
            *scale = number;
            return 0;
        }
    }
    return -1;
}
#endif
